version: "3"

services:   
  mongo:
    image: mongo:5.0.5
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      

  mongo-express:
    image: mongo-express
    env_file:
      - .env
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:${DB_PORT}" 
  
  api:
    build: ./api/
    ports:
      - 3000:3000
    volumes:
      - ./api/app.js:/app/app.js
      - ./api/routes/:/app/routes/
      - ./api/models/:/app/models/
      - ./api/utils/:/app/utils/
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo-express
      - mongo
    command: bash -c "node ./data/populate.js && nodemon ./app.js"